from vingereKeywordLength import *
from formulaShtuff import *

import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = [7.50, 3.50]
plt.rcParams["figure.autolayout"] = True

alphabet = [chr(97 + i) for i in range(0,26)]

text = """YOHAP IEVFW WIZBU NWVGJ TMZKY FTNII URDGV IAIRT TNAIJ JDOCI JCZWM JYJII QEOHV WANYZ SGHSR GOPHK MEICK JTCOK IRRVZ YEYWJ HOQSI JDDBK MEWWE IIIUF KTCSS TOFTF ZNYPP NSGSJ XBJRP NCVBE TTNSV MORMF ZCJIC ITCWE PIRCL QDFBF BAIMK MIIUR GOPHZ YAIRZ KIIRZ YESHI JMZZP ZNGWB JLTHY FTDHT TUGRY FVZPV JNRFZ YTZBS DAIMF SEDBD DHJIJ JHJZU DOPFT QADAK MAOHY JCCOI FCOSI NSOWT XOAHY JTTDV HAIPV ZSZRK TIYSE YIAMK MENCL WCZOJ YHZHP UERFZ YEMKV MOGRZ STCSD FNNWF SSZSD XTJAV YOWSU NVDBR YIJBE TTNQZ JNXSR SDRWK MOPHD ZCCGK WOIUV WEQWU JNXSF KAGWE PBZHN JEIGF REJBV NNHMY TUNSY TLYOE ITCSP TUIUD FNDGC JSDKZ QLICK JNOSI YADBF WCJCG JRVHV BIOVR SYAII YHZFZ SVZGK NGVHZ TNNWY FVZOC WEVRP JXKFV XSZRD DCJBJ YEMBR YIJBR YTCSG WONDV HTJTR XCVBU FLYSI FIGWE LMTQR RPVWX SFJFJ YAOSX TVZFE TRVBU NTCCL LHOHY FTTCL ZNYSI XTJCU FNYOX WEZRN NTCAV BHTMF ZWJIC IWVBK YOMSF UEIHY JCVGV BHZBZ MAQSJ TMPQY YOGCJ JAIRN JHVJV SOOVZ SGOCX FIITI TMDHZ HAIBF YUIRV WSOOE IIFBF BTCOK RADGZ JHVGS JEIDI JSNWE LFJFW ZROVV WIIJV XTDUR YIJBR SDDHZ XCGSR WTCOK XHZKR XDZSG QYYWJ YRZGJ JDWMK MERVF QEDBT NDZBK XHZZF AENHY JLDPI FRTOE IWJIC IDJOE DTCWE LTJDI TTZQK NTCCN JVZFJ MEDGD JRZZP FSZFM FNOCW YHZSJ YAOSR SDNII JLTAP XTVHL XANDI JSZBK TWISI LIQSJ LRZOK JRRSZ LHOHF RYQWV BSVBU BINVV XWCWC JINZV XCGSR WLTHI JSKOJ XEYVV XEZAJ SOOHF MAQST FUNSU FNTRR RABSR SDZJV SIAVV BANWE YEIRZ SGOCJ YEVZW WOHAV MINIE YIHSC DDZOK MFJFV XTVZC JDOVR YPGOE MECOJ FLMSR IYKOZ ITCSG WIXSW TRCWJ RINRV JDNOE IIYCE TTNSV FNTFV FSJBK TCJBK NNPSK TPJYV FNYDI TBZOK BHVHD ZSOGL WEGMS JAMCL YIIST FSZWD ZSOWE XINHK MAOMF ZBMWE LAAWE FLCOC YTJMF ZRDBM JSOWX FTDCE XAIRC JTCWD WENHZ SPZOT JLZHL XNJHZ SVDHV LONGZ UAOHY NSXFZ YIXOC YIHSP TUMGZ SFMWV SDNVZ URJUV WS"""

text = text.replace(" ", "").replace("\n", "").lower()
textLength = len(text)

keywordLength, differences = getEstimatedKeywordLength(text, 10)

print(keywordLength)

keywordLength = 5

focused = 4

cosets = splitCosets(keywordLength, text)
focusedCoset = cosets[focused]

frequencies = frequency(focusedCoset)
percentageFrequencies = [(freq / textLength) for freq in frequencies]

plt.figure(1)
plot = plt.bar(alphabet, percentageFrequencies)

plt.figure(2)
plot2 = plt.bar(alphabet, ENG_LETTER_FREQ)

plt.show()