import sys
sys.path.append("C:\\Users\\justa\\Documents\\Coding\\CodingFolder\\Cryptography")

import matplotlib.pyplot as plt
import cryptotools as ct

text = """AIYNA GKRCT ELUOI SGAEE LLSON OKONS NAAOT OWDSM SEAAT OEPNC EDTLV UNTRL IDDTH HEPTE FAIAD GOSWR EMUIR EINMO USRSG SIEHN YARSR ESNOR ROEDR ELEON PESEE HUAEM AIOCR BRMEI ISFEL TNIRT EYLVA OTTTE SROTR NWAOI QIIKN EANTO AETNT TIEOE TNTFU NIDFE ETMSR TMHEO CDIEE AYECY FIOHE SAPEC NRLDW DNSII LNTGE IOAAD SEEBS EDOUA SLITR TESRO SOSTA LEEIA YAGLN YOESO EAROO AMEOS NISGA IAHAL NSTEC ITTEU CDRSI WLGMN ITEMP ENNED WVUFY LLSNV YRDEE ELTRT ALODP ISSDP RSNTY LASED EPTRP ODNCI CBNAR NAYHS POAAL VYLEO ARRDI LNSSY IIECO ADEUE ETEAP ADSAP BREPO LSTIF LECCI VERSA EDOOC WRSGO OEUEN NOCLQ EFEES NRRCA RDQOS AACRR PLNIE HSTEB EMTER SDNLY ATREO TNMER TNELN LAIUI TFEEN TGIFL ISWDE NCMSE """
text = text.replace(" ","").replace("\n","").lower()

textLength = len(text)

cipher_freq = ct.frequency(text)
cipher_freq = [freq / textLength for freq in cipher_freq]

plt.figure(1)
plot1 = plt.bar(ct.ALPHABET, ct.ENG_LETTER_FREQ)

plt.figure(2)
plot2 = plt.bar(ct.ALPHABET, cipher_freq)

plt.show()