import sys
sys.path.append("C:\\Users\\justa\\Documents\\Coding\\Public\\CodingFolder\\Cryptography")

import cryptotools as ct
from digram_scores import *

text = """POKUI LIEXI NTFAW BIVYH KFWVG APIBZ EDVAG ARZYI PMVFX WRKOC PHRAO ENXLS QFFEE CRVRM JGKBG KNKVR QENVX DTYRM JVVFX EGRGM KNKBX DIJCS ENKNR ZFFEJ KRNNV ZIETC KUISM JDZAK OINNW OHFPO ADKBL AAINF KUKGL ASZGY WTZBR KFDLI IPCBC ARSHX JOKGL WTJHV LRZFI ZTFEI WDFSL ESRZF ETZBR POJRV RERFK KVVER KRFSS QRJGE PEKUE PHRFF AEENR KPVAW ACIRX ENKUI DOLFI DOCQJ KRJBQ ATZZI PHFHK DIYNH JOKEI WLZFI ZTYNX DENNW ENKRR ZIETX KSKNR ZFFEX DEFSJ ECVJL ANZGR AXKOI YADRZ WCRAX ENDLQ ENUUM OADOM PIFAA WSDBV AABVR POURW ERVNR ZIKUM JKDNR UOWHW WSJHQ ADKUE PHVJS QLURM PHVEJ WLCVR POKUI LOJGS NTYNX ETNBY HDGNW OHZZF UIKQM ZNFGS YCLEX KMVGL WTYRA KUCQX WKVNG PIMRW PEGFX KTILX KSNNC PHVRP ACKBV WTVNR ZIYNH YEIGE ENCLR KTTBR OIURV ADKUE PHVZM CHKBJ BEIBY NMREZ ALCBY OCFYP ACKVS JTFGL ANVJT NOMVH ANTRP EBINV UIEBV ZEIGS XUPVR BLLRR YERAH OUGCS NTYRL WSEBX ZIJPY OSVQM PWZGL IEKUS QGYVW DOLYH DAMRK QEJFI ZTYNX OODRX DIETA WSRSS KTNUI JHVNW GEUZI POYRP LVRYY ATYRF KOBFJ KRRAM JSLEE JCVCS HITLA AHRII XEVAG KVVEI ZFFEJ ERVNR ZIETI JEINP BOIGL AFKFM JCVOI BOIRM FOZAI ZTYRL KUJRL KLUOY PAJVL WVVNG MUZEI ZSVII NACII NYGEI YIFHW PEOGW ENIRG ANKLI WRJVX OEVZI ZNRGY NACSS NTYRQ POSRE ZDVQX KTYRT KLZPC EDZQR KTKUM JKKBU QEJGM KNNUC ETNNW JETRW OAILX KRVIE HUVGL AWYBP ACFYP ACKVS JBLGM OUGCS OEKUE PTYVW IIXUX DAMRJ KRDRH LAIGS BTYRH ESTHW OIFAW XEKJI ANYVQ WNUGL ACZGC KFWVG EACFE HLFSX DIJZE GEJFI JSVOY PDFRW JOKRB LLRVR PHVCV ASVAG AOWZV ESCRW ENDLP EBINV UTYNX IOIAM JGPBY DAMRW QGXRW PEUGL WTYRQ EGYGL WVVOI ANJGI WLZAK KRZAX ANUVR CTFFX AACVX AMJSV KMDRF QTPBY DAMRR KTJNM ZHFJL AKERA PHRGA AHVYH PHVZQ UUEQI NSKNR ZIETM OTYNX PHVOS KKJRP HEIFA DOGNM ZFFEL ESGNW OAXRW LETVE HIJRM JPIBG QRZAK OPVPM BITEE NEZGI ISFSM JCLAE XUCNJ KRTBP HETGS NSFAE YODZM OSZBR XAJVW BOIGL AMKBL WVVFI JTDEM OLVFE YRFFW PHVBG AAEFY CGVFX OTYNX PHVLO JENNP NERQC SHZPL ETVZW SEYRP ZHVEI WNUVG WNRFW QRVLS QTYNX KNCLE BENCI KPCRL WVVNG YEJFX KOLEG WTRYS CIJVX LOJFM XLVGL WTDEV KGVEW CAMRE YCVFW POKUI YAKNP KGKBX DETVX UFRGL ARJGS EMGEI OSLCS JTYRQ PHVUM CHMNP QEFSX DEXVJ PHVJE OMRXM JGTBY HDFAI KFKUI IHRII XEVAM JCFAW LIING UWZGL PHVNP NEJSS NDTBQ LAELX KMRXI KFWJM PHJBQ AOWBY NMFEI RACHE XLVVX AMJBV ESZGT KSJVF HEKUE POERS BTYRL KUJRL KLUPS QLUUE RESRI JIEGI JDZAK POGES BIKGL APIRW ANTRS BTYRM JSLEE JCVIE HUVEW SAJAS PSFZI PHZAK SERQZ ARKVW ADSHX ENRFQ WLCPS IMLAM PYCVO AOLEW ETNBY HDEBX DAMRF AEENW ACIRX WNUVX IAPUE REVAG KUINK ADCNV YEEBY OTYBY CHKFM BYFHL WVVNR USLTK ASKVS JSWBV BUIGL ARZAK KUIRR MUZEM ASZJS QLUOI IOJGT HERFI ZTFUI WRKUI IYFHV OFRVX DFLYP UMJZW PYCRW """.replace(" ", "").replace("\n", "").upper()
key_length = 11

cosets = ct.splitCosets(key_length, text)
cosets2 = cosets.copy()

coset_length = len(cosets[0])
output = []

for i in cosets:
    for j in cosets2:
        sum = 0
        for row in range(0,coset_length-1):
            lambda_ = i[row]
            mu = j[row]

            plm = digram_scores_dict[f"{lambda_}{mu}"]
            sum += plm
        sum /= coset_length-1
        output.append(f"{i[0]} {j[0]} {sum}\n")

with open("Cryptography\\ColumnarTransCipher\\output.txt","w") as file:
    file.writelines(output)






