import sys
sys.path.append("C:\\Users\\justa\\Documents\\Coding\\Public\\CodingFolder\\Cryptography")

import cryptotools as ct
import matplotlib.pyplot as plt

# take text input and format it
text = """NEWSOBAIWMQIWXSAXGIRBWSUWZBSIRQOBPBBSNXVBGVLWIGLHIRQSWUXLHZRQOBRXDBZDWSCBVIXSARQOBDVXOWZBZUHBQVBOWZBSUBIRQIIRBVBTQAQUXSADWVQUEIXAIBQHGVXNNEHWPVQVEQSZIRQIBOWZBSUBDXWSIAIXNEBNDHXEBVXVQIHBQAIAXNBXSBWSRWABNDHXENBSINVVXMBVARQZDHQSSBZIXZXSQIBIRBUXHHBUIWXSIXIRBUWIEHWPVQVEWSXVZBVIXDVXNXIBRWAUQNDQWMSGXVBHBUIWXSIXMXOBVSXVPLIIRBPXXCAQVBGQVIXXOQHLQPHBIXMWOBQTQEQSZWIWABQAEIXPBHWBOBIRQIRBTXLHZRQOBIVWBZIXVBQHWABAXNBXGIRQIOQHLBGXVRWNABHGBADBUWQHHEAWSUBQSBHBUIWXSWAQSBYDBSAWOBPLAWSBAAWSXLVAIQIBIRBVBQVBQZOBVIWABNBSIAIXDLVURQABQSZWSGHLBSIWQHDBXDHBTRXSBBZIXPBUXSOWSUBZIXPQUCRWNWIWANEZLIEQAULAIXZWQSXGIRBUXHHBUIWXSIXDVXIBUIWIWUQSSXIHBIRWNZBAIVXEBOBVEIRWSMTBRQOBPLWHIIXMBIRBVWITQANERXDBIRQIPEMQIRBVWSMBSXLMRBOWZBSUBIXWSUVWNWSQIBRWNWUXLHZUXSOWSUBNVVXMBVAIXHBQOBIRBHWPVQVEQHXSBWRQOBADBSIEBQVAULVQIWSMWIQSZWIUXSIQWSANQSEDVBUWXLAWIBNAWUXLHZSXIPBQVIXHXABWIWRQOBARXTSRWNIRBHBIIBVAGVXNDWSCBVIXSAQSZIVWBZIXVBQAXSTWIRRWNRBWAOBVEQSMVETWIRNBQSZCBBDAAQEWSMIRQIIRBZBQIRQSZIRBQIIBNDIBZIRBGIRQZSXIRWSMIXZXTWIRRWNRBWAVWMRIIRQIIRBVBWASXIRWSMUXSUHLAWOBWSIRBBOWZBSUBPLIQAWDXWSIBZXLIIXRWNIRBVBZXBASXISBBZIXPBQSEDVXXGBOBSIRBALADWUWXSXGRWAWSOXHOBNBSITXLHZABOBVBHEZQNQMBRWAVBDLIQIWXSQSZTXLHZZBAIVXERWAURQSUBXGBHBUIWXSRBRQAIRVBQIBSBZIXGWVBNBPLIWIWAQSBNDIEIRVBQIRBUQSSXIQGGXVZGXVNBIXIQHCIXIRBDVBAALSIWHRBQMVBBAIXNEZBNQSZAWTWHHUXSIWSLBIXRQVQAARWNQSZIXPLWHZNEBOWZBSUBNEHWPVQVENLAIPBDVXIBUIBZQIQHHUXAIA"""
text = text.replace(" ", "").replace("\n", "").lower()
textLength = len(text)

# get english and cipher frequencies and decimals of 1
cipher_freqencies = ct.frequency(text)
cipher_freqencies = [frequency/textLength for frequency in cipher_freqencies]
english_frequencies = ct.ENG_LETTER_FREQ

# order an alphabet list by those frequencies
english_ordered_alphabet = [x for _, x in sorted(zip(english_frequencies, ct.ALPHABET))]
cipher_ordered_alphabet = [x for _, x in sorted(zip(cipher_freqencies, ct.ALPHABET))]

english_ordered_alphabet.reverse()
cipher_ordered_alphabet.reverse()

# sort the actual frequencies in the same way (by themself)
english_frequencies.sort(reverse=True)
cipher_freqencies.sort(reverse=True)

# i don't know why this is here but i love it and am going to keep it anyway
print("hello")

# plot english letter frequencies and cipher letter frequencies (both sorted) for comparison
plt.figure(1)
english_plot = plt.bar(english_ordered_alphabet, english_frequencies)

plt.figure(2)
cipher_plot = plt.bar(cipher_ordered_alphabet, cipher_freqencies)

print("".join(cipher_ordered_alphabet))

plt.show()




